name: Tag version

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    permissions: write-all
    name: Tag version and push to repo
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.VERSION_TAGGING_TOKEN }}
          fetch-depth: 0
          fetch-tags: true
          
      - name: git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          
      - name: Get version, update and tag
        run: $GITHUB_WORKSPACE/version.sh
        shell: bash
